paths:
  /api/products:
    get:
      summary: Get all products
      tags:
        - Products
      responses:
        "200":
          description: All products were read correctly
        "500":
          description: Internal server error

    post:
      summary: Create a new product
      tags:
        - Products
      parameters:
        - in: body
          name: product
          required: true
          description: New product data
          schema:
            type: object
            properties:
              title:
                type: string
                description: Product title
              price:
                type: number
                description: Product price
              stock:
                type: number
                description: Product stock
              code:
                type: string
                description: Product code
              description:
                type: string
                description: Product description
      responses:
        "200":
          description: Successfully created product
        "401":
          description: Unauthorized
        "500":
          description: Internal server error

  /api/products/{pid}:
    get:
      summary: Get product by Id
      tags:
        - Products
      parameters:
        - name: pid
          in: path
          description: product id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: The product was read correctly
        "500":
          description: Internal server error

    put:
      summary: Update product
      tags:
        - Products
      parameters:
        - name: pid
          in: path
          required: true
          description: product id
          schema:
            $type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#components/requestBodies/updateProduct"
      responses:
        "200":
          description: This product was successfully updated
        "401":
          description: Unauthorized
        "500":
          description: Internal server error

    delete:
      summary: Delete a product by id
      tags:
        - Products
      parameters:
        - name: pid
          in: path
          required: true
          description: product id
          schema:
            $type: string
      responses:
        "200":
          description: The product was disposed of correctly
        "401":
          description: Unauthorized
        "500":
          description: Internal server error

components:
  schemas:
    Product:
      type: object
      properties:
        _id:
          type: ObjectId
          description: Product ID autogenerated by the database
        title:
          type: string
          description: Product title
        price:
          type: number
          description: Product price
        stock:
          type: number
          description: Product stock
        code:
          type: string
          description: Product code
        description:
          type: string
          description: Product description
      example:
        _id: ObjectId('64e53fb25d35dda3aab57f85')
        title: Producto 100
        price: 5252
        stock: 100
        code: AAA100
        description: descripcion del producto 100

  requestBodies:
    updateProduct:
      type: object
      properties:
        title:
          type: string
          description: Product title
        price:
          type: number
          description: Product price
        stock:
          type: number
          description: Product stock
        code:
          type: string
          description: Product code
        description:
          type: string
          description: Product description
      example:
        title: Producto 100
        price: 5252
        stock: 100
        code: AAA100
        description: descripcion del producto 100
